# Set the log level
# The log level can be set with the environment variable TF_LOG. 
# You need to export the variable with the correct log level. 
# Here is an example of where TF_LOG is set with DEBUG level:

$ export TF_LOG=”DEBUG”

# Verify the log level:

$ echo $TF_LOG
DEBUG

# Set up log file using TF_LOG_PATH 

export TF_LOG_PATH="/home/vagrant/terraform-ec2-aws/<ou can name and choose the log file path as per your requirement.>"

# Verify the logs generated by Terraform
# Apply to chechk the result:

cat terraform-debug.log <the name choosen for your log>

#  Using the error_message to validate variable value